const siteConfig = {
  name: "Budva Car Hire",
  tagline: "Drive the Montenegrin Riviera",
  domain: "budvacarhire.com",
  phone: "",
  email: "info@budvacarhire.com",
  address: "Tabacina BB, Kotor, 85330",

  hero: {
    headline: "Budva Car Hire — Drive the Riviera",
    subheadline: "Rent a car in Budva from Tivat Airport (22 km). Beaches, Old Town, Sveti Stefan — all within reach.",
    image: "/img/hero-budva.webp",
  },

  cars: [
    {
      id: 1,
      slug: "peugeot-208",
      typeGroup: "economy",
      name: "Peugeot 208",
      category: "Economy",
      tagline: "Stylish French supermini that carves the Sveti Stefan hairpins",
      lede: "Distinctive 208 Mk2 — small, sharp, the small-car choice for drivers who care what they're sitting in.",
      price: 26,
      image: "/img/fleet/peugeot-208.jpg",
      seats: 5,
      transmission: "Manual",
      fuel: "Petrol",
      doors: 4,
      luggage: 2,
      ac: true,
      features: ["3D i-Cockpit", "Apple CarPlay", "Cruise Control", "Lane Assist"],
      details: {
        engine: "1.2 PureTech 3-cyl turbo petrol",
        power: "100 hp",
        consumption: "5.1 L/100 km",
        bootSize: "311 L",
        length: "4,055 mm",
        topSpeed: "188 km/h",
        acceleration: "9.9s (0–100 km/h)",
        driveType: "Front-wheel drive",
      },
      popular: false,
      bestFor: ["Couples", "Design-led renters", "Coastal-road drivers"],
      suitability: "Two travellers who want a small car that feels like an event rather than an appliance — the 208 has the sharpest chassis at this end of the riviera fleet.",
      regional: "Light nose, small turning circle and a tiny steering wheel that makes the Sveti Stefan hairpins and the single-track above Pržno feel bespoke. Lively on the E80 to Petrovac; at 4,055 mm still slots into the Slovenska summer bays without drama.",
    },
    {
      id: 2,
      slug: "renault-clio",
      typeGroup: "economy",
      name: "Renault Clio",
      category: "Economy",
      tagline: "The default Budva rental — compact, cheap to fuel, easy to park at Bečići",
      lede: "Most common rental on the riviera. Five doors, 391-litre boot, built for the Jaz-to-Petrovac routine.",
      price: 28,
      image: "/img/fleet/renault-clio.jpg",
      seats: 5,
      transmission: "Manual",
      fuel: "Petrol",
      doors: 4,
      luggage: 2,
      ac: true,
      features: ["Bluetooth Audio", "USB Charging", "Central Locking", "Touchscreen Display"],
      details: {
        engine: "1.0 TCe 3-cyl turbo petrol",
        power: "100 hp",
        consumption: "5.3 L/100 km",
        bootSize: "391 L",
        length: "4,050 mm",
        topSpeed: "188 km/h",
        acceleration: "11.8s (0–100 km/h)",
        driveType: "Front-wheel drive",
      },
      popular: true,
      bestFor: ["First-time riviera visitors", "Couples", "Short coastal stays"],
      suitability: "Two travellers with cabin bags doing Budva, Sveti Stefan and a day trip to Kotor. The workhorse of the riviera rental fleet.",
      regional: "Fits the pay-by-hour bays along Slovenska, threads the single-track lane down to Kamenovo, and holds 110 km/h on the E80 stretch toward Bar without fuss. The default riviera choice for a reason.",
    },
    {
      id: 3,
      slug: "fiat-500",
      typeGroup: "economy",
      name: "Fiat 500",
      category: "City",
      tagline: "Tiny postcard city car for the Stari Grad perimeter and Mogren back lanes",
      lede: "Parks where nothing else fits — ideal for stays anchored in Budva, Bečići or Rafailovići.",
      price: 20,
      image: "/img/fleet/fiat-500.jpg",
      seats: 4,
      transmission: "Manual",
      fuel: "Petrol",
      doors: 2,
      luggage: 1,
      ac: true,
      features: ["Compact Size", "Easy Parking", "Sunroof", "Bluetooth"],
      details: {
        engine: "1.0 L mild-hybrid petrol",
        power: "70 hp",
        consumption: "5.4 L/100 km",
        bootSize: "185 L",
        length: "3,571 mm",
        topSpeed: "167 km/h",
        acceleration: "13.8s (0–100 km/h)",
        driveType: "Front-wheel drive",
      },
      popular: false,
      bestFor: ["Solo travellers", "Short Budva stays", "Photographers"],
      suitability: "One or two travellers staying inside Budva — where summer parking is brutal and most trips are under 20 km along the riviera.",
      regional: "The only car that genuinely slips into the back lanes behind Mogren Beach. A photographer's companion: sunroof open at the Sveti Stefan overlook, boot just big enough for a tripod bag and a beach towel.",
    },
    {
      id: 4,
      slug: "peugeot-308",
      typeGroup: "midsize",
      name: "Peugeot 308",
      category: "Mid-Size",
      tagline: "Grown-up French mid-size — diesel torque for the Budva-to-Dubrovnik run",
      lede: "Quiet BlueHDi diesel, proper long-legged cruiser with a 412-litre boot — the family-of-four default.",
      price: 38,
      image: "/img/fleet/peugeot-308.jpg",
      seats: 5,
      transmission: "Automatic",
      fuel: "Diesel",
      doors: 4,
      luggage: 3,
      ac: true,
      features: ["Automatic Transmission", "Adaptive Cruise", "Dual-Zone Climate", "Large Boot"],
      details: {
        engine: "1.5 BlueHDi 4-cyl diesel",
        power: "130 hp",
        consumption: "4.4 L/100 km",
        bootSize: "412 L (1,309 L seats folded)",
        length: "4,367 mm",
        topSpeed: "206 km/h",
        acceleration: "10.1s (0–100 km/h)",
        driveType: "Front-wheel drive, 8-spd auto",
      },
      popular: false,
      bestFor: ["Families of four", "Road-trippers", "Cross-border drivers"],
      suitability: "Four adults with luggage, or a family with a pushchair. Diesel plus auto plus cruise is the combination for riviera-based trips that include Dubrovnik or Skadar.",
      regional: "Eats the E80 south to Bar at a steady 110 without fuss, has the boot for beach gear to Jaz and day-trip kit to Durmitor on the same visit. Comfortable on the 80 km cross-border push to Dubrovnik via Debeli Brijeg.",
    },
    {
      id: 5,
      slug: "kia-stonic",
      typeGroup: "suv",
      name: "Kia Stonic",
      category: "Compact Crossover",
      tagline: "Raised ride height without the rental SUV price — the back-road compromise",
      lede: "352-litre boot, higher ride than a hatch, modest 1.0-litre petrol — the crossover for the Lovćen road and the Skadar Lake spur.",
      price: 40,
      image: "/img/fleet/kia-stonic.jpg",
      seats: 5,
      transmission: "Manual",
      fuel: "Petrol",
      doors: 4,
      luggage: 3,
      ac: true,
      features: ["Raised Ride Height", "Apple CarPlay", "Reversing Camera", "Lane Keep Assist"],
      details: {
        engine: "1.0 T-GDi 3-cyl turbo petrol",
        power: "100 hp",
        consumption: "5.5 L/100 km",
        bootSize: "352 L (1,155 L seats folded)",
        length: "4,140 mm",
        topSpeed: "183 km/h",
        acceleration: "10.7s (0–100 km/h)",
        driveType: "Front-wheel drive",
      },
      popular: false,
      bestFor: ["Couples heading inland", "Day-trip hoppers", "Budget crossover renters"],
      suitability: "Renters who want a higher driving position and a little more ground clearance for inland detours from Budva, without paying premium-SUV money.",
      regional: "The extra ride height takes the edge off the patched tarmac above Petrovac and on the spur to the Skadar wine villages, and the boot swallows enough gear for an overnight in Cetinje. Front-wheel drive only — pick this for dry summer tracks, not winter snow up to Žabljak.",
    },
    {
      id: 6,
      slug: "vw-golf",
      typeGroup: "midsize",
      name: "VW Golf",
      category: "Mid-Size",
      tagline: "The benchmark hatch — DSG diesel that handles every riviera journey adequately",
      lede: "Polo's agility, 308's distance-eating ability — the rational default for most Budva trips.",
      price: 42,
      image: "/img/fleet/vw-golf.jpg",
      seats: 5,
      transmission: "Automatic",
      fuel: "Diesel",
      doors: 4,
      luggage: 3,
      ac: true,
      features: ["DSG Automatic", "Adaptive Cruise", "Digital Cockpit", "Apple CarPlay"],
      details: {
        engine: "2.0 L TDI diesel (Mk8)",
        power: "150 hp",
        consumption: "4.3 L/100 km",
        bootSize: "381 L (1,237 L seats folded)",
        length: "4,287 mm",
        topSpeed: "223 km/h",
        acceleration: "8.4s (0–100 km/h)",
        driveType: "Front-wheel drive, 7-spd DSG auto",
      },
      popular: false,
      bestFor: ["Solo and couple travellers", "Mixed riviera + inland trips", "Quick Tivat Airport transfers"],
      suitability: "Couples or small families who want Polo-style town agility plus the long-distance refinement for runs to Podgorica or Dubrovnik — without stepping up to an SUV.",
      regional: "Threads the Budva ring road at school-run pace and then settles at 120 on the Sozina tunnel approach to Bar. 4.3 L/100 km on the coastal cruise to Ulcinj, and the DSG picks the right gear on the Cetinje switchbacks before you think about it.",
    },
    {
      id: 7,
      slug: "toyota-yaris",
      typeGroup: "economy",
      name: "Toyota Yaris",
      category: "Economy",
      tagline: "Cheapest to fuel in the fleet — the hybrid sips petrol in Budva stop-start",
      lede: "3.8 L/100 km in real use. The Yaris Hybrid costs roughly half what a diesel mid-size does per kilometre.",
      price: 34,
      image: "/img/fleet/toyota-yaris.jpg",
      seats: 5,
      transmission: "Automatic",
      fuel: "Hybrid",
      doors: 4,
      luggage: 2,
      ac: true,
      features: ["Hybrid Drivetrain", "Reversing Camera", "Apple CarPlay", "Adaptive Cruise"],
      details: {
        engine: "1.5 VVT-i Hybrid petrol–electric",
        power: "116 hp combined",
        consumption: "3.8 L/100 km",
        bootSize: "286 L",
        length: "3,940 mm",
        topSpeed: "175 km/h",
        acceleration: "9.7s (0–100 km/h)",
        driveType: "Front-wheel drive (e-CVT)",
      },
      popular: true,
      bestFor: ["Fuel-conscious travellers", "Urban-focused trips", "Stop-start riviera driving"],
      suitability: "Travellers who want to drive a fortnight on half the fuel bill. The hybrid pays for itself on the slow summer crawl through Budva and Bečići.",
      regional: "Pure-electric rolling through Bečići's 30 km/h zone at dawn, then glides to Sveti Stefan without touching the fuel needle. Don't pick it for long mountain climbs toward Kolašin where the battery drains on the grade.",
    },
  ],

  features: [
    { icon: "map-pin", title: "Tivat Airport Pickup", description: "Tivat Airport sits 22 km up the coast from Budva. Your agent is waiting at arrivals — one coast road drive and you're parking on the riviera." },
    { icon: "shield-check", title: "Full Insurance", description: "CDW and theft cover included as standard. Upgrade to zero excess if you want total peace of mind on narrow coastal lanes and tight beach car parks." },
    { icon: "clock", title: "24/7 Support", description: "Left your lights on at Jaz Beach car park? Locked your keys in at Mogren? Call us any hour — we know every car park on this riviera." },
    { icon: "ban", title: "No Hidden Fees", description: "One number at booking. That same number at pickup. VAT, mileage, and beach-town fuel policy are all baked in — nothing added at the counter." },
    { icon: "refresh-cw", title: "Free Cancellation", description: "Summer weather on the riviera shifts fast, and festival dates change. Cancel free up to 24 hours before your pickup and get every cent refunded." },
    { icon: "globe", title: "Cross-Border Ready", description: "Dubrovnik is 2.5 hours north via Debeli Brijeg. The Albanian border is closer from Budva than from anywhere else on the riviera. Green card sorted at booking." },
  ],

  testimonials: [
    { name: "Aoife & Conor", location: "Dublin, Ireland", text: "We drove from Jaz Beach to Sveti Stefan on our first morning and couldn't believe the views. Stopped at Bečići for lunch, made it to the Sveti Stefan viewpoint before sunset. The car meant we could dodge the buses and go at our own pace. Would absolutely book again.", rating: 5, avatar: "/img/avatar-1.webp" },
    { name: "Erik, Jonas & Linn", location: "Stockholm, Sweden", text: "Three of us rented for five nights — Top Hill one evening, Trocadero the next, then a road trip south to Petrovac for a slower afternoon. Having a car meant no waiting for taxis at 2am. The agent at Tivat was quick and the car was spotless. Exactly what we needed.", rating: 5, avatar: "/img/avatar-2.webp" },
    { name: "Heidi & Walter", location: "Zürich, Switzerland", text: "We prefer quieter roads and olive groves to beach clubs. The car took us south to Petrovac, through the old village lanes above Budva, and along the coast at our own gentle pace. The old town in the evenings was magical. A very well organised rental from start to finish.", rating: 5, avatar: "/img/avatar-3.webp" },
  ],

  faq: [
    { q: "What documents do I need to rent?", a: "You'll need a full driving licence with Latin-script details, your passport, and a physical credit card issued in the main driver's name. If your licence is from a country that uses a non-Latin script, bring an International Driving Permit as well. Photocopies and digital-only licences are not accepted at pickup." },
    { q: "Can I drive to Croatia or Albania?", a: "Yes. Cross-border travel is permitted to Croatia, Bosnia, Albania, Kosovo, and Serbia. The Dubrovnik day trip via Debeli Brijeg is one of the most popular runs from Budva — about 2.5 hours each way. Just flag the countries at booking and the Green Card is prepared for you." },
    { q: "Is there a minimum age to rent?", a: "Age and licence experience requirements vary by vehicle class and are listed clearly in each car's details when you search. Younger drivers may see a small daily supplement depending on the model." },
    { q: "What's actually included in the price?", a: "Third-party liability insurance and CDW come standard on most cars. VAT, a roadside safety kit, and a transparent fuel policy are included too. Mileage terms differ per vehicle — check the car listing. Zero-excess cover and extras like child seats can be added at booking." },
    { q: "How does pickup work at Tivat Airport?", a: "Your agent meets you at Tivat Airport arrivals hall. The 22 km coast road to Budva takes around 25 minutes depending on summer traffic. No shuttle, no waiting around — the car is parked right outside the terminal." },
    { q: "Can I return the car somewhere different?", a: "One-way rentals are available across 28+ towns and cities in Montenegro. Pick up at Tivat, drop off in Budva, or vice versa — just select different locations when you book." },
    { q: "What is the cancellation policy?", a: "Standard vehicles: free cancellation up to 7 days before pickup. Luxury cars and convertibles: free cancellation up to 30 days in advance. A 6% processing fee applies on all cancellations regardless of timing." },
    { q: "Do I need to pay a deposit?", a: "It depends on the vehicle. Deposits typically fall between €100 and €500 for most riviera rentals. Some cars require no deposit at all. Where one applies, it sits on the main driver's physical credit card and is released when the car is returned undamaged." },
    { q: "What if I go over my mileage allowance?", a: "Vehicles with a set mileage cap charge a per-kilometre fee for any distance above the limit. The exact overage rate is shown in the car details before you confirm — no surprises." },
    { q: "Is the price I see the price I pay?", a: "Yes. All taxes and standard fees are folded into the booking price. There is no fuel surcharge, airport levy, or desk fee added when you collect the car." },
    { q: "How much do I pay to confirm the booking?", a: "A deposit of roughly 15% to 20% of the total secures the reservation. The rest is settled directly with the rental agent when you pick up the car in Budva or at Tivat." },
    { q: "Can I rent without a credit card?", a: "Certain vehicles in the fleet can be rented with a debit card or without a card altogether. These are labelled in the search results so you can filter accordingly." },
  ],

  locations: [
    { name: "Budva Old Town", tag: "Most Popular" },
    { name: "Tivat Airport", tag: "22 km" },
    { name: "Bečići", tag: "" },
    { name: "Sveti Stefan", tag: "" },
  ],

  destinations: [
    {
      name: "Tivat Airport",
      slug: "tivat-airport",
      tag: "22 km Away",
      desc: "The closest airport to Budva. We meet you at arrivals.",
      image: "/img/tivat-airport.webp",
    },
    {
      name: "Kotor",
      slug: "kotor",
      tag: "UNESCO Site",
      desc: "Medieval walled city, 25 km from Budva.",
      image: "/img/kotor-nearby.webp",
    },
    {
      name: "Budva",
      slug: "budva",
      tag: "Home Base",
      desc: "Old Town, beaches, and the heart of the riviera.",
      image: "/img/budva-old-town.webp",
    },
    {
      name: "Podgorica Airport",
      slug: "podgorica-airport",
      tag: "Capital Hub",
      desc: "Montenegro's main international airport, 65 km away.",
      image: "/img/podgorica-airport.webp",
    },
    {
      name: "Tivat",
      slug: "tivat",
      tag: "Marina Town",
      desc: "Porto Montenegro and stunning Boka Bay.",
      image: "/img/porto-montenegro.webp",
    },
    {
      name: "Perast",
      slug: "perast",
      tag: "Hidden Gem",
      desc: "Baroque village on the Bay of Kotor.",
      image: "/img/perast-village.webp",
    },
    {
      name: "Dubrovnik Airport",
      slug: "dubrovnik-airport",
      tag: "Cross-Border",
      desc: "Fly into Dubrovnik, drive to Budva.",
      image: "/img/dubrovnik-nearby.webp",
    },
    {
      name: "Podgorica",
      slug: "podgorica",
      tag: "Capital City",
      desc: "Montenegro's modern capital — culture and commerce.",
      image: "/img/podgorica-city.webp",
    },
  ],
};

export default siteConfig;
